/**
 * TaskManagerV2 — Era 2 adversarial test suite.
 *
 * The proven path runs against the REAL EZKL Halo2VerifierReusable compiled
 * from the spike circuit, with REAL proofs generated by the spike's three
 * distinct trained models (test/fixtures/era2_testdata.json). Every gauntlet
 * card has a test here before it gets a UI: ghost, copycat, stale challenge,
 * tampered proof, forged score, Sybil flood.
 *
 * A minimal mock verifier covers ranking edge cases (exact ties) that real
 * model scores can't be forced to produce on demand.
 */
const { expect } = require("chai");
const { ethers } = require("hardhat");
const fixture = require("./fixtures/era2_testdata.json");

const FIELD_PRIME =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n;

function toSigned(felt) {
  const v = BigInt(felt);
  return v <= FIELD_PRIME / 2n ? v : v - FIELD_PRIME;
}

/** JS reference implementation of the contract's signed-field argmax scoring. */
function expectedScore(instances, labels) {
  let correct = 0;
  for (let img = 0; img < 8; img++) {
    let bestVal = toSigned(instances[1 + img * 10]);
    let bestDigit = 0;
    for (let d = 1; d < 10; d++) {
      const v = toSigned(instances[1 + img * 10 + d]);
      if (v > bestVal) { bestVal = v; bestDigit = d; }
    }
    if (bestDigit === labels[img]) correct++;
  }
  return Math.floor((correct * 100) / 8);
}

function vkaDigestOf(vka) {
  return ethers.keccak256(ethers.concat(vka));
}

function batchDigestOf(commitments, labels) {
  return ethers.keccak256(
    ethers.AbiCoder.defaultAbiCoder().encode(
      ["uint256[]", "uint256[]"],
      [commitments, labels]
    )
  );
}

const commitments = fixture.batches.map((b) => BigInt(b.commitment));
const packedLabels = fixture.batches.map((b) => BigInt(b.packedLabels));

async function deployStack() {
  const [operator, alice, bob, carol] = await ethers.getSigners();

  const Token = await ethers.getContractFactory("POLToken");
  const token = await Token.deploy();

  const Verifier = await ethers.getContractFactory("Halo2VerifierReusable");
  const verifier = await Verifier.deploy();
  await verifier.registerVka(fixture.vka);

  const Manager = await ethers.getContractFactory("TaskManagerV2");
  const manager = await Manager.deploy(
    await token.getAddress(),
    await verifier.getAddress(),
    vkaDigestOf(fixture.vka),
    batchDigestOf(commitments, packedLabels),
    2
  );
  await manager.loadBatches(commitments, packedLabels);
  await manager.seal();

  await token.approve(await manager.getAddress(), ethers.MaxUint256);
  // fund alice so she can post tasks permissionlessly
  await token.transfer(alice.address, ethers.parseEther("10000"));
  await token.connect(alice).approve(await manager.getAddress(), ethers.MaxUint256);

  return { token, verifier, manager, operator, alice, bob, carol };
}

/** Post a 1-hour task and return its id + assigned challenge batch. */
async function post(manager, signer, threshold = 0) {
  const deadline = (await ethers.provider.getBlock("latest")).timestamp + 3600;
  const tx = await manager.connect(signer).postTask(
    "Era-2 test task", threshold, ethers.parseEther("100"), deadline,
    ethers.id("model-lineage")
  );
  const rc = await tx.wait();
  const ev = rc.logs.map((l) => { try { return manager.interface.parseLog(l); } catch { return null; } })
    .find((p) => p && p.name === "TaskPosted");
  return { taskId: ev.args.taskId, batchIdx: Number(ev.args.batchIdx) };
}

/** The fixture proof matching a task's batch (we have real proofs for both batches). */
function proofForBatch(batchIdx, which = "primary") {
  if (batchIdx === 1) return fixture.proofs.batch1;
  const order = ["global", "variant_a", "variant_b", "variant_c"];
  if (which === "primary") return fixture.proofs.global;
  return fixture.proofs[which] || fixture.proofs[order[1]];
}

/** A valid proof for the OTHER batch — the stale-challenge forgery. */
function proofForOtherBatch(batchIdx) {
  return batchIdx === 1 ? fixture.proofs.global : fixture.proofs.batch1;
}

function labelsForBatch(batchIdx) {
  return fixture.batches[batchIdx].labels;
}

describe("TaskManagerV2 — Era 2", function () {
  this.timeout(180_000); // real Halo2 verification is heavy for hardhat's EVM

  // ------------------------------------------------------------------
  // Setup & sealing
  // ------------------------------------------------------------------
  describe("setup and seal", () => {
    it("rejects sealing when loaded data does not match the pinned digest", async () => {
      const [op] = await ethers.getSigners();
      const Token = await ethers.getContractFactory("POLToken");
      const token = await Token.deploy();
      const Manager = await ethers.getContractFactory("TaskManagerV2");
      const manager = await Manager.deploy(
        await token.getAddress(), op.address, ethers.ZeroHash,
        batchDigestOf(commitments, packedLabels), 2
      );
      // tamper one label before loading
      await manager.loadBatches(commitments, [packedLabels[0] + 1n, packedLabels[1]]);
      await expect(manager.seal()).to.be.revertedWithCustomError(manager, "BatchDataMismatch");
    });

    it("is inert before seal and ownerless after", async () => {
      const { manager, operator, alice } = await deployStack();
      expect(await manager.isSealed()).to.equal(true);
      expect(await manager.setupOperator()).to.equal(ethers.ZeroAddress);
      // no further loading possible, by anyone — including the original operator
      await expect(manager.connect(operator).loadBatches([1n], [1n]))
        .to.be.revertedWithCustomError(manager, "NotSetupOperator");
      await expect(manager.connect(alice).loadBatches([1n], [1n]))
        .to.be.revertedWithCustomError(manager, "NotSetupOperator");
    });
  });

  // ------------------------------------------------------------------
  // The headline: proven submissions with REAL proofs
  // ------------------------------------------------------------------
  describe("proven submissions (real EZKL verifier, real proofs)", () => {
    it("accepts a real proof and computes the score on-chain from the logits", async () => {
      const { manager, alice, bob } = await deployStack();
      const { taskId, batchIdx } = await post(manager, alice);
      const p = proofForBatch(batchIdx);

      const tx = await manager.connect(bob).submitWithProof(
        taskId, ethers.id("gradient"), p.proof, p.instances, fixture.vka
      );
      const rc = await tx.wait();
      console.log(`      ⛽ submitWithProof (real Halo2 verify): ${rc.gasUsed} gas`);

      const sub = await manager.getSubmission(taskId, 0);
      expect(sub.zkVerified).to.equal(true);
      expect(sub.miner).to.equal(bob.address);

      const expected = expectedScore(p.instances, labelsForBatch(batchIdx));
      expect(Number(sub.score)).to.equal(expected);
      console.log(`      📊 contract score ${sub.score} == JS reference ${expected}`);
    });

    it("has no score parameter anywhere in the proven path (ABI-level)", async () => {
      const { manager } = await deployStack();
      const fn = manager.interface.getFunction("submitWithProof");
      expect(fn.inputs.map((i) => i.name)).to.deep.equal(
        ["taskId", "gradientHash", "proof", "instances", "vka"]
      );
    });
  });

  // ------------------------------------------------------------------
  // The gauntlet — every card is a test before it is a UI
  // ------------------------------------------------------------------
  describe("adversarial gauntlet", () => {
    it("GHOST OF ERA 1 — an archived Era-1 proof dies on instance length (794 ≠ 81)", async () => {
      const { manager, alice, bob } = await deployStack();
      const { taskId } = await post(manager, alice);
      await expect(
        manager.connect(bob).submitWithProof(
          taskId, ethers.id("ghost"),
          fixture.era1_ghost.proof, fixture.era1_ghost.instances, fixture.vka
        )
      ).to.be.revertedWithCustomError(manager, "BadInstanceLength");
    });

    it("STALE CHALLENGE — your own valid proof from another batch dies on commitment", async () => {
      const { manager, alice, bob } = await deployStack();
      const { taskId, batchIdx } = await post(manager, alice);
      const stale = proofForOtherBatch(batchIdx);
      await expect(
        manager.connect(bob).submitWithProof(
          taskId, ethers.id("stale"), stale.proof, stale.instances, fixture.vka
        )
      ).to.be.revertedWithCustomError(manager, "ChallengeMismatch");
    });

    it("COPYCAT — byte-copying a confirmed proof dies on the nullifier", async () => {
      const { manager, alice, bob, carol } = await deployStack();
      const { taskId, batchIdx } = await post(manager, alice);
      const p = proofForBatch(batchIdx);
      await manager.connect(bob).submitWithProof(
        taskId, ethers.id("honest"), p.proof, p.instances, fixture.vka
      );
      await expect(
        manager.connect(carol).submitWithProof(
          taskId, ethers.id("copied"), p.proof, p.instances, fixture.vka
        )
      ).to.be.revertedWithCustomError(manager, "ProofAlreadyUsed");
    });

    it("TAMPERED PROOF — one flipped byte dies in the verifier", async () => {
      const { manager, alice, bob } = await deployStack();
      const { taskId, batchIdx } = await post(manager, alice);
      const p = proofForBatch(batchIdx);
      const bytes = ethers.getBytes(p.proof);
      bytes[1000] ^= 0xff;
      await expect(
        manager.connect(bob).submitWithProof(
          taskId, ethers.id("tampered"), ethers.hexlify(bytes), p.instances, fixture.vka
        )
      ).to.be.revertedWithCustomError(manager, "InvalidProof");
    });

    it("FORGED LOGITS — inflating an output instance dies in the verifier", async () => {
      const { manager, alice, bob } = await deployStack();
      const { taskId, batchIdx } = await post(manager, alice);
      const p = proofForBatch(batchIdx);
      const forged = [...p.instances];
      forged[5] = "0x" + (123456789n).toString(16).padStart(64, "0");
      await expect(
        manager.connect(bob).submitWithProof(
          taskId, ethers.id("forged"), p.proof, forged, fixture.vka
        )
      ).to.be.revertedWithCustomError(manager, "InvalidProof");
    });

    it("WRONG VKA — an unpinned verifying key dies before the verifier is even called", async () => {
      const { manager, alice, bob } = await deployStack();
      const { taskId, batchIdx } = await post(manager, alice);
      const p = proofForBatch(batchIdx);
      const wrongVka = [...fixture.vka];
      wrongVka[0] = ethers.ZeroHash;
      await expect(
        manager.connect(bob).submitWithProof(
          taskId, ethers.id("badvka"), p.proof, p.instances, wrongVka
        )
      ).to.be.revertedWithCustomError(manager, "BadVka");
    });

    it("FORGED SCORE — a claimed 99 lands, then loses at finalize to any real proof", async () => {
      const { manager, alice, bob, carol } = await deployStack();
      const { taskId, batchIdx } = await post(manager, alice);
      // carol forges a 99 via the unproven path — this is allowed to land
      await manager.connect(carol).submitWork(taskId, ethers.id("forged-99"), 99);
      // bob proves honestly; on-chain score will be ≤ 100 but PROVEN
      const p = proofForBatch(batchIdx);
      await manager.connect(bob).submitWithProof(
        taskId, ethers.id("honest"), p.proof, p.instances, fixture.vka
      );
      await ethers.provider.send("evm_increaseTime", [3601]);
      await manager.connect(carol).finalizeTask(taskId); // permissionless, even the attacker can crank it
      const task = await manager.getTask(taskId);
      expect(task.winner).to.equal(bob.address);
    });

    it("SYBIL FLOOD — claim #17 is rejected, and a prover still gets in afterward", async () => {
      const { manager, alice, bob } = await deployStack();
      const { taskId, batchIdx } = await post(manager, alice);
      const signers = await ethers.getSigners();
      // 16 distinct sybils fill the unverified cap (signers[4..19])
      for (let i = 0; i < 16; i++) {
        await manager.connect(signers[4 + i]).submitWork(taskId, ethers.id(`sybil${i}`), 90);
      }
      await expect(
        manager.connect(signers[3]).submitWork(taskId, ethers.id("sybil17"), 90)
      ).to.be.revertedWithCustomError(manager, "SubmissionCapReached");
      // the flood cannot lock out a proof
      const p = proofForBatch(batchIdx);
      await manager.connect(bob).submitWithProof(
        taskId, ethers.id("prover"), p.proof, p.instances, fixture.vka
      );
      expect(await manager.provenCount(taskId)).to.equal(1n);
    });
  });

  // ------------------------------------------------------------------
  // Ranking, settlement, refunds (mock verifier for forced exact scores)
  // ------------------------------------------------------------------
  describe("ranking and settlement", () => {
    async function deployMockStack() {
      const [op, alice, bob, carol, dave] = await ethers.getSigners();
      const Token = await ethers.getContractFactory("POLToken");
      const token = await Token.deploy();
      const Mock = await ethers.getContractFactory("MockVerifierV2");
      const mock = await Mock.deploy();
      const Manager = await ethers.getContractFactory("TaskManagerV2");
      // mock stack uses an empty vka: digest of empty packed bytes
      const manager = await Manager.deploy(
        await token.getAddress(), await mock.getAddress(),
        ethers.keccak256("0x"),
        batchDigestOf([1n, 2n], [BigInt(fixture.batches[0].packedLabels), BigInt(fixture.batches[1].packedLabels)]),
        2
      );
      await manager.loadBatches([1n, 2n], [BigInt(fixture.batches[0].packedLabels), BigInt(fixture.batches[1].packedLabels)]);
      await manager.seal();
      await token.approve(await manager.getAddress(), ethers.MaxUint256);
      return { token, manager, op, alice, bob, carol, dave };
    }

    /** Synthetic instances: commitment + logits that argmax to `digits`. */
    function synthInstances(commitment, digits) {
      const inst = [commitment];
      for (let img = 0; img < 8; img++) {
        for (let d = 0; d < 10; d++) {
          inst.push(d === digits[img] ? 1000n : 1n);
        }
      }
      return inst.map((v) => "0x" + BigInt(v).toString(16).padStart(64, "0"));
    }

    function labelsFromPacked(packed) {
      const out = [];
      for (let i = 0; i < 8; i++) out.push(Number((BigInt(packed) >> BigInt(i * 4)) & 0xfn));
      return out;
    }

    it("equal proven scores tie-break by keccak(taskId, proofHash), not order", async () => {
      const { manager, op, bob, carol } = await deployMockStack();
      const { taskId, batchIdx } = await post(manager, op);
      const labels = labelsFromPacked(fixture.batches[batchIdx].packedLabels);
      const commitment = batchIdx === 0 ? 1n : 2n;
      const inst = synthInstances(commitment, labels); // 100 for both

      const proofA = ethers.hexlify(ethers.randomBytes(64));
      const proofB = ethers.hexlify(ethers.randomBytes(64));
      await manager.connect(bob).submitWithProof(taskId, ethers.id("a"), proofA, inst, []);
      await manager.connect(carol).submitWithProof(taskId, ethers.id("b"), proofB, inst, []);

      const key = (proofBytes) => BigInt(ethers.keccak256(
        ethers.AbiCoder.defaultAbiCoder().encode(["uint256", "bytes32"], [taskId, ethers.keccak256(proofBytes)])
      ));
      const expectedWinner = key(proofA) < key(proofB) ? bob.address : carol.address;

      await ethers.provider.send("evm_increaseTime", [3601]);
      await manager.finalizeTask(taskId);
      expect((await manager.getTask(taskId)).winner).to.equal(expectedWinner);
    });

    it("a 12-score proof beats a 99-score claim; claimed ranking is score-then-earliest", async () => {
      const { manager, op, alice, bob, carol, dave } = await deployMockStack();
      const { taskId, batchIdx } = await post(manager, op);
      const labels = labelsFromPacked(fixture.batches[batchIdx].packedLabels);
      const commitment = batchIdx === 0 ? 1n : 2n;
      // proof scoring exactly 1/8 correct = 12
      const oneRight = labels.map((l, i) => (i === 0 ? l : (l + 1) % 10));
      const inst = synthInstances(commitment, oneRight);

      await manager.connect(alice).submitWork(taskId, ethers.id("c99"), 99);
      await manager.connect(dave).submitWork(taskId, ethers.id("c99b"), 99);
      await manager.connect(bob).submitWithProof(
        taskId, ethers.id("p12"), ethers.hexlify(ethers.randomBytes(64)), inst, []
      );
      const sub = await manager.getSubmission(taskId, 2);
      expect(Number(sub.score)).to.equal(12);

      await ethers.provider.send("evm_increaseTime", [3601]);
      await manager.connect(carol).finalizeTask(taskId);
      const task = await manager.getTask(taskId);
      expect(task.winner).to.equal(bob.address); // 12 PROVEN > 99 CLAIMED
    });

    it("refunds the poster (not an owner) when a task gets no submissions", async () => {
      const { token, manager, alice } = await deployMockStack();
      await token.transfer(alice.address, ethers.parseEther("100"));
      await token.connect(alice).approve(await manager.getAddress(), ethers.MaxUint256);
      const before = await token.balanceOf(alice.address);
      const { taskId } = await post(manager, alice);
      await ethers.provider.send("evm_increaseTime", [3601]);
      await manager.finalizeTask(taskId);
      expect(await token.balanceOf(alice.address)).to.equal(before);
      expect((await manager.getTask(taskId)).winner).to.equal(ethers.ZeroAddress);
    });

    it("cannot finalize before deadline, cannot finalize twice, one submission per address", async () => {
      const { manager, op, bob } = await deployMockStack();
      const { taskId } = await post(manager, op);
      await expect(manager.finalizeTask(taskId))
        .to.be.revertedWithCustomError(manager, "TaskNotExpired");
      await manager.connect(bob).submitWork(taskId, ethers.id("x"), 50);
      await expect(manager.connect(bob).submitWork(taskId, ethers.id("y"), 60))
        .to.be.revertedWithCustomError(manager, "AlreadySubmitted");
      await ethers.provider.send("evm_increaseTime", [3601]);
      await manager.finalizeTask(taskId);
      await expect(manager.finalizeTask(taskId))
        .to.be.revertedWithCustomError(manager, "AlreadyFinalized");
    });

    it("anyone may post a task — there is no owner to ask", async () => {
      const { token, manager, dave } = await deployMockStack();
      await token.transfer(dave.address, ethers.parseEther("100"));
      await token.connect(dave).approve(await manager.getAddress(), ethers.MaxUint256);
      const { taskId } = await post(manager, dave);
      expect((await manager.getTask(taskId)).poster).to.equal(dave.address);
    });
  });
});
