// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";

/// @dev Minimal interface for the EZKL-generated Halo2Verifier contract.
interface IVerifier {
    function verifyProof(bytes calldata proof, uint256[] calldata instances) external returns (bool);
}

/// @title TaskManager — Proof of Learning Mining Protocol
/// @notice Owner posts training tasks with POL rewards; miners submit gradient
///         hashes and performance scores; highest scorer after the deadline wins.
///         Miners may optionally attach a ZK proof generated by EZKL to
///         cryptographically prove their inference was run correctly.
contract TaskManager {
    struct Task {
        uint256 id;
        string description;
        uint256 threshold;      // minimum score (0-100) required to submit
        uint256 reward;         // POL tokens (in wei) locked for this task
        uint256 deadline;       // unix timestamp after which finalize is allowed
        bool finalized;
        address winner;         // set after finalization
    }

    struct Submission {
        address miner;
        bytes32 gradientHash;
        uint256 score;          // 0-100
        uint256 submittedAt;
        bool zkVerified;        // true if submission included a valid EZKL proof
    }

    IERC20 public immutable polToken;
    address public owner;
    address public verifier;    // Halo2Verifier contract; set via setVerifier()
    uint256 private _taskCounter;

    mapping(uint256 => Task) public tasks;
    mapping(uint256 => Submission[]) private _submissions;

    event TaskPosted(uint256 indexed taskId, string description, uint256 threshold, uint256 reward, uint256 deadline);
    event WorkSubmitted(uint256 indexed taskId, address indexed miner, bytes32 gradientHash, uint256 score);
    event ZKWorkSubmitted(uint256 indexed taskId, address indexed miner, bytes32 gradientHash, uint256 score);
    event TaskFinalized(uint256 indexed taskId, address indexed winner, uint256 reward);
    event VerifierSet(address indexed verifier);

    modifier onlyOwner() {
        require(msg.sender == owner, "TaskManager: not owner");
        _;
    }

    constructor(address _polToken) {
        owner = msg.sender;
        polToken = IERC20(_polToken);
    }

    /// @notice Set or update the EZKL Halo2Verifier contract address.
    function setVerifier(address _verifier) external onlyOwner {
        verifier = _verifier;
        emit VerifierSet(_verifier);
    }

    /// @notice Post a new training task. Caller must have approved `reward` POL to this contract first.
    function postTask(
        string calldata description,
        uint256 threshold,
        uint256 reward,
        uint256 deadline
    ) external onlyOwner returns (uint256) {
        require(threshold <= 100, "TaskManager: threshold exceeds 100");
        require(deadline > block.timestamp, "TaskManager: deadline in the past");
        require(reward > 0, "TaskManager: reward must be nonzero");

        require(polToken.transferFrom(msg.sender, address(this), reward), "TaskManager: reward transfer failed");

        uint256 taskId = ++_taskCounter;
        tasks[taskId] = Task({
            id: taskId,
            description: description,
            threshold: threshold,
            reward: reward,
            deadline: deadline,
            finalized: false,
            winner: address(0)
        });

        emit TaskPosted(taskId, description, threshold, reward, deadline);
        return taskId;
    }

    /// @notice Trust-based submission — score is self-reported, no cryptographic proof.
    function submitWork(
        uint256 taskId,
        bytes32 gradientHash,
        uint256 score
    ) external {
        _validateSubmission(taskId, score);

        _submissions[taskId].push(Submission({
            miner: msg.sender,
            gradientHash: gradientHash,
            score: score,
            submittedAt: block.timestamp,
            zkVerified: false
        }));

        emit WorkSubmitted(taskId, msg.sender, gradientHash, score);
    }

    /// @notice ZK-verified submission — calls the Halo2Verifier to confirm the
    ///         proof before accepting. The proof cryptographically guarantees that
    ///         the reported score was produced by a correct forward pass over the
    ///         committed model weights (which remain private).
    /// @param proof     Raw proof bytes from EZKL's proof.json `hex_proof` field.
    /// @param instances Public circuit inputs/outputs (feature vector + logit),
    ///                  each as a big-endian uint256. Convert from proof.json's
    ///                  little-endian hex strings by reversing byte order.
    function submitWithProof(
        uint256 taskId,
        bytes32 gradientHash,
        uint256 score,
        bytes calldata proof,
        uint256[] calldata instances
    ) external {
        _validateSubmission(taskId, score);
        require(verifier != address(0), "TaskManager: verifier not configured");
        require(IVerifier(verifier).verifyProof(proof, instances), "TaskManager: invalid ZK proof");

        _submissions[taskId].push(Submission({
            miner: msg.sender,
            gradientHash: gradientHash,
            score: score,
            submittedAt: block.timestamp,
            zkVerified: true
        }));

        emit ZKWorkSubmitted(taskId, msg.sender, gradientHash, score);
    }

    /// @notice Finalize a task after its deadline. Highest scorer wins; ties go
    ///         to the first submitter. No submissions refunds the owner.
    function finalizeTask(uint256 taskId) external onlyOwner {
        Task storage task = tasks[taskId];
        require(task.id != 0, "TaskManager: task does not exist");
        require(!task.finalized, "TaskManager: task already finalized");
        require(block.timestamp >= task.deadline, "TaskManager: deadline not reached");

        task.finalized = true;

        Submission[] storage subs = _submissions[taskId];
        if (subs.length == 0) {
            require(polToken.transfer(owner, task.reward), "TaskManager: refund failed");
            emit TaskFinalized(taskId, address(0), 0);
            return;
        }

        uint256 bestIndex = 0;
        for (uint256 i = 1; i < subs.length; i++) {
            if (subs[i].score > subs[bestIndex].score) {
                bestIndex = i;
            }
        }

        address winner = subs[bestIndex].miner;
        task.winner = winner;

        require(polToken.transfer(winner, task.reward), "TaskManager: reward transfer failed");
        emit TaskFinalized(taskId, winner, task.reward);
    }

    // -------------------------------------------------------------------------
    // Read functions
    // -------------------------------------------------------------------------

    function getTask(uint256 taskId) external view returns (Task memory) {
        require(tasks[taskId].id != 0, "TaskManager: task does not exist");
        return tasks[taskId];
    }

    function getSubmissionCount(uint256 taskId) external view returns (uint256) {
        return _submissions[taskId].length;
    }

    function getSubmission(uint256 taskId, uint256 index) external view returns (Submission memory) {
        require(index < _submissions[taskId].length, "TaskManager: index out of bounds");
        return _submissions[taskId][index];
    }

    function getAllSubmissions(uint256 taskId) external view returns (Submission[] memory) {
        return _submissions[taskId];
    }

    function totalTasks() external view returns (uint256) {
        return _taskCounter;
    }

    // -------------------------------------------------------------------------
    // Internal
    // -------------------------------------------------------------------------

    function _validateSubmission(uint256 taskId, uint256 score) internal view {
        Task storage task = tasks[taskId];
        require(task.id != 0, "TaskManager: task does not exist");
        require(!task.finalized, "TaskManager: task already finalized");
        require(block.timestamp < task.deadline, "TaskManager: deadline passed");
        require(score <= 100, "TaskManager: score exceeds 100");
        require(score >= task.threshold, "TaskManager: score below threshold");
    }
}
